services:
  frontend:
    image: weather-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    image: weather-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5174:5000"
    volumes:
      - ./backend:/app
      - ./database:/data
    environment:
      - DATABASE_PATH=/data/weather.db
    command: ["npm", "run", "dev"]